### PR TITLE
Add a driver...

### PR DESCRIPTION
**Pull request by Blackcode**
Tutorial on how to add a driver to windows

### CODE REVIEW

**Comment by Blackcode** [comment]
hummmmm can you explain me why I see all the commits and not just mine?

**Comment by zfields** [comment]
You probably need to "rebase" your branch from upstream/develop

**Comment by Blackcode** [comment]
I am kinda new to git... still experimenting with it.. and sometime I do mistakes

**Comment by ooeygui** [comment]
(I made this error too)
We have description of how to rebase in our contribute doc:
http://ms-iot.github.io/content/Contribute.htm

Unfortunately, we can't move forward without the rebase complete otherwise it creates history loops. If you have issues with rebasing, I'll be on IRC this afternoon, ping me (same account name)

**Comment by ooeygui** [comment]
Oh, and very cool post!

**Comment by Blackcode** [comment]
I saw the documentation but I am stuck I opened a notepad with text and do not know what to do here I will try to reach ya on IRC or I will figure a way.

pick cc8c19d Added UART Sample and Added Advanced Usage around UART port
pick 7baf896 Add a driver to Windows
Rebase 93a7013..7baf896 onto 93a7013
Commands:
p, pick = use commit
r, reword = use commit, but edit the commit message
e, edit = use commit, but stop for amending
s, squash = use commit, but meld into previous commit
f, fixup = like "squash", but discard this commit's log message
x, exec = run command (the rest of the line) using shell

These lines can be re-ordered; they are executed from top to bottom.

If you remove a line here THAT COMMIT WILL BE LOST.

However, if you remove everything, the rebase will be aborted.

Note that empty commits are commented out

**Comment by ooeygui** [comment]
The rebase goes into an 'incomplete' state. This means that there is a file which has a merge conflict. If you use git status, you can find the file with the conflict. You have to edit the file and manually merge the change (remove all of the <<<< and >>> comments.). Once you do this, you have to rerun your tests to verify it has your changes and the other persons'. You then continue the rebase (git rebase --continue) You can resubmit afterward.

Here's a doc on merging:
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line

**Comment by Blackcode** [comment]
I will refork I did not managed to get out of this

**Pull request closed without merging**
