### PR TITLE
Update AllJoyn.md

### PR DESCRIPTION
**Pull request by kcc1988**
Added back Alljoyn Explorer links as well as links to the tutorial pages

### CODE REVIEW

**Comment by ghost** [comment]
Hi **@kcc1988**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by ghost** [comment]
Hi **@kcc1988**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by kcc1988** [comment]
@jonbgallant  @sungow Request to merge ASAP, fixed 2 broken image links, now linked to correct versions of AJX; also added links to the tutorials and Alljoyn Explorer back to Alljoyn.md page

**Comment by kcc1988** [comment]
Thank you!

**Pull request merged**
