### PR TITLE
IO Expansion ShieldV7 Serial Bluetooth and Button communication

### PR DESCRIPTION
**Pull request by Shak7**
I got started with Windows through the Windows Developer Program for IoT last week, using Galileo Gen2. After finishing some of the "Getting Started" tutorials (many thanks), I was now ready to move forward by myself. Looking around for something to tinker with and getting fast results, I gathered from my stuff the DFRobot IO Expansion Shield V7, a Bluetooth Bee, a button, a 10k resistor and some wires. Added the code to build exe and get a serial Bluetooth communication test between the Galileo and a computer or Windows Phone, via hardware serial, and for testing, an answer when the button is pushed. Fell free to give any advice, this is my first pull request of all time.

### CODE REVIEW

**Comment by ooeygui** [comment]
Thank you for your pull request! I'll run through it on Monday and give you feedback or pull it.
Because this is larger than a bug fix, did you happen to fill out the contribution license agreement?  https://cla.msopentech.com/.

**Comment by Shak7** [comment]
Hi,

Yes, I filled out the agreement and went through the process before I
pulled the request, I used my GitHub username.

Thank you,

2014-12-13 17:57 GMT-05:00 Lou Amadio notifications@github.com:

> Thank you for your pull request! I'll run through it on Monday and give
> you feedback or pull it.
> Because this is larger than a bug fix, did you happen to fill out the
> contribution license agreement? https://cla.msopentech.com/.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ms-iot/content/pull/137#issuecomment-66894990.

## 

Patrick Coutu
514-371-9412
patrick.coutu@gmail.com

**Comment by zfields** [comment]
Wow, great work! Thank you for taking the time to write this up.

Before we can pull your work, I noticed a few things we need to fix.

First, you need to link to your page from SampleApps.md.

Second, there are a handful of formatting issues. It can be difficult to know what your markdown is going to look like, but you have a couple of options. You can install Jekyll on your machine and render it locally, or you can simply cross-push your work into the gh-pages branch of your repository (i.e. `git push -f origin develop:gh-pages`). Then you can go to the url "https://shak7.github.io/content" to see it rendered.

Next, it looks like you have accidentally commited the thumbs.db file, which should be removed from the history of your commits (not just removing it with another commit, otherwise it is held forever). Don't worry, if this is beyond your Git skill level, I would be happy to help.

Lastly, this CAN merge cleanly, but for most commits (including this one) you will need to rebase from upstream/develop so you can catch up with changes that occurred while you were working.

If you need any help with anything I have described, please write back with specific questions for more information.

Thank you for contributing!
Zak

**Comment by Shak7** [comment]
Hi Zak,

Many thanks, your reply is very helpful.

As you asked, I added my link from SampleApps.md

About removing the thumbs.db file (sorry for that), I would ask you for
some help, as I guess that if I remove the commit line using git rebase, it
will remove everything from that commit...(?) I got to see some hints, but
nothing very clear.

From now I will work on the files locally, before I push my next commit.

Thanks again!
Patrick

2014-12-15 20:41 GMT-05:00 Zachary J. Fields notifications@github.com:

> Wow, great work! Thank you for taking the time to write this up.
> 
> Before we can pull your work, I noticed a few things we need to fix.
> 
> First, you need to link to your page from SampleApps.md.
> 
> Second, there are a handful of formatting issues. It can be difficult to
> know what your markdown is going to look like, but you have a couple of
> options. You can install Jekyll on your machine and render it locally, or
> you can simply cross-push your work into the gh-pages branch of your
> repository (i.e. git push -f origin develop:gh-pages). Then you can go to
> the url "https://shak7.github.io/content" to see it rendered.
> 
> Next, it looks like you have accidentally commited the thumbs.db file,
> which should be removed from the history of your commits (not just removing
> it with another commit, otherwise it is held forever). Don't worry, if this
> is beyond your Git skill level, I would be happy to help.
> 
> Lastly, this CAN merge cleanly, but for most commits (including this one)
> you will need to rebase from upstream/develop so you can catch up with
> changes that occurred while you were working.
> 
> If you need any help with anything I have described, please write back
> with specific questions for more information.
> 
> Thank you for contributing!
> Zak
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ms-iot/content/pull/137#issuecomment-67099528.

## 

Patrick Coutu
514-371-9412
patrick.coutu@gmail.com

**Comment by ooeygui** [comment]
We should have thumbs.db in our .gitignore. I'll get that fixed.
1. Use `git rm thumbs.db` to remove that file. 
2. Then `git commit`
3. Then `git rebase -i upstream/develop`
4. Then you can `git push -f origin develop`

This last line will update the pull request.

**Comment by Shak7** [comment]
Thanks for the instructions, very appreciated,

OK, I created a branch called "rework", before "4c2388". Then, using "git
checkout rework" the output is "D  images/Thumbs.db", as if when I will do
next commit, this file will be deleted...

When I add the correct files and then if check the status, I never get "M
filename" return, as if I have to commit the deletion before I add
anything. The return is always "D  images/Thumbs.db".

I tried to delete the rework branch and redo it, it gives me the same
result.  :-(

You said not to delete and commit... so I guess I'm stuck there.

Thanks to all for the help. Yep, I'm really learning something here !

2014-12-17 3:47 GMT-05:00 Zachary J. Fields notifications@github.com:

> The easiest way to alter history (i.e. "uncommit" thumbs.db file - not
> delete and commit), is to create a branch (let's call it "rework" for this
> example) at the commit (4c2388a
> https://github.com/ms-iot/content/commit/4c2388ab230fcf6febc3d08f84bfca0d8c8aee72)
> before the offending commit (98847eb
> https://github.com/ms-iot/content/commit/98847eb0c29fc4f8ab53e32140b291ccbe552a6d).
> Then add the correct files, everything except thumbs.db (if you add each
> file individually this is much easier). Commit those files, then "cherry
> pick" the remaining commits from "develop" into your new "rework" branch.
> 
> Again, you can check your work by cross-pushing "rework" into "gh-pages"
> (i.e. git push -f origin rework:gh-pages). If everything looks good, then
> you can simply rename "develop" to "_develop", and "rework" to "develop"
> then force push develop back to origin (i.e. git push -f origin develop);
> now you've rewritten history with no thumbs.db.
> You won't need to issue a new pull-request, as the changes will be
> reflected in your current request.
> 
> If this is still too difficult, then just let me know, and I will issue a
> pull request to you showing you what I'm looking for and you can simply
> accept it and everything will be ready to go. :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ms-iot/content/pull/137#issuecomment-67292726.

## 

Patrick Coutu
514-371-9412
patrick.coutu@gmail.com

**Comment by ooeygui** [comment]
Completely removing files from git requires a bit of git-fu.

Try reading up on git filter-branch: 
[https://help.github.com/articles/remove-sensitive-data/](https://help.github.com/articles/remove-sensitive-data/)

**Comment by Shak7** [comment]
A bit of progress; I removed the delete label from the branch. Back to "M
images/Thumbs.db", instead of "D  images/Thumbs.db".

Will read some more about branches, commits and getting it done. I know I'm
not far.

Thanks for the link, that helped.

In the meantime, Happy Holidays !

2014-12-17 11:49 GMT-05:00 Lou Amadio notifications@github.com:

> Completely removing files from git requires a bit of git-fu.
> 
> Try reading up on git filter-branch:
> https://help.github.com/articles/remove-sensitive-data/
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ms-iot/content/pull/137#issuecomment-67352531.

## 

Patrick Coutu
514-371-9412
patrick.coutu@gmail.com

**Comment by ooeygui** [comment]
Sorry for the delay in responding. (the whole team has been out sick!).
When you get a chance, could you refresh the pull request? It is currently out of date.

**Comment by zfields** [comment]
Hi Shak7!

I would like to propose a solution to clean up your commit history before we pull your changes. Since the majority of your commits are tweaks with the same commit message, we would like to see you clean up the commits in your pull-request so it makes sense in (and doesn't bloat) our history.

The easiest solution is to reset to the commit before your first commit with `--mixed` specified, then you can make a single clean commit, that can be reviewed, rebased and merged much more easily.

Follow these steps to compress your work into a single commit*:
1. `git reset --mixed 450374aa12eb3568b7f057b54d00e934072041dc`
2. `rm images/Thumbs.db`
3. `git add .`
4. `git commit -m "Expansion ShieldV7 Serial Bluetooth Button" -m "Tutorial about getting started with the DFRobot IO Expansion Shield V7, a BluetoothBee and a button."`

Next you will need to rebase to sync up with the latest changes:
1. `git rebase upstream/develop`
2. You will encounter a merge conflict. I resolved it by leaving the section marked `<<<<<<< HEAD` and adding the following as the last tile of the sixth row:
    `<div class="col-md-4">`
    `<h2>IO Shield with Bluetooth and Button</h2>`
    `<span class="label label-info">New</span>`
    `<p>Learn how to use the DFRobot IO Expansion Shield V7 with Bluetooth and Button.</p>`
    `<p><a class="btn btn-default" href="IoExpansionShieldV7BluetoothBeeButton.htm" role="button">View details &raquo;</a></p>`
    `</div>`
3. `git rebase --continue`

Then you can review your work on GitHub, by force pushing your branch to gh-pages:
`git push -f origin develop:gh-pages`
Your work will appear on [your GitHub account](http://shak7.github.io/content/SampleApps.htm)

> > You might notice you are missing a line ending near the "From Windows Phone: " caption. ;-)

Finally, you can overwrite your history on GitHub, by force pushing your branch to develop:
`git push -f origin develop`

Now your pull-request will reflect the changes, and you are ready to go!

Let me know if any of these directions are confusing or need clarification!

Thanks again,
Zak

*Please note, it is not a requirement that you only have a single commit if you want to contribute to our project, however in this scenario a single commit does a better job of conveying the intent of the work.

**Comment by zfields** [comment]
So far, so good! I added a link to your gh-pages so you can see your work. :-)

**Comment by zfields** [comment]
So I know I told you to use `git add .`, but it looks like it picked up a file called `content`. What is that file? I don't think we want it. Can you remove it as well?

**Comment by zfields** [comment]
I'm following your repo. I see you were able to flatten your commits :+1: , but now you seem to be hung up. Are you waiting for the weekend, or is there anything I can help you with?

**Comment by Shak7** [comment]
Hi,

Thanks for the help,

Yes, I will get through it during the weekend. Very busy till tomorrow...

2015-01-09 12:44 GMT-05:00 Zachary J. Fields notifications@github.com:

> I'm following your repo. I see you were able to flatten your commits [image:
> :+1:] , but now you seem to be hung up. Are you waiting for the weekend,
> or is there anything I can help you with?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ms-iot/content/pull/137#issuecomment-69370012.

## 

Patrick Coutu
514-371-9412
patrick.coutu@gmail.com

**Comment by ooeygui** [comment]
How is this change coming?

**Comment by Shak7** [comment]
Hi Lou,

After trying to get through, I could not say I wasted my time, I've learned
a lot about git, my last commit always seems to be one that I wanted to
remove just before.

I always get back to push a commit I don't want. Where there is a double
"content" folder to be removed, I remove, rebase and then it adds in
another commit on top with the content folder that we don't want.

So, has I read somewhere. Can I just save my local files and redo this all
over in github ? And at the same time, the pull requests will be cleaner.

I don't know, since the thumb.db problem, I'm in a swam of troubles with
this one. It's me, somewhere certainly missing some commands.

Many thanks,

2015-01-22 13:57 GMT-05:00 Lou Amadio notifications@github.com:

> How is this change coming?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ms-iot/content/pull/137#issuecomment-71076747.

## 

Patrick Coutu
514-371-9412
patrick.coutu@gmail.com

**Comment by zfields** [comment]
Shak I'm tinkering tonight. I will walk you through it, if you would like to contact me, just email zachary_fields@yahoo.com.

**Comment by ooeygui** [comment]
Would you mind updating this pull and resubmitting?

**Pull request closed without merging**
