### PR TITLE
Update SetupWiFi.md

### PR DESCRIPTION
**Pull request by volkansarioglu**
TP-LINK TL_WN725N not same in all country and last release dot have a driver for it.

### CODE REVIEW

**Comment by ooeygui** [comment]
Hi @volkansarioglu, your change added (only minnowboard) to a wifi dongle. However, that column is only for minnowboard, so the clarification does not appear needed. Can you clarify?

**Comment by volkansarioglu** [comment]
yes. Thanks.

**Comment by daveraskin** [comment]
@ooeygui has your original concern been addressed? Is this ready to merge?

**Comment by HerrickSpencer** [comment]
I believe this change should not be merged, as the table already defines the item as for MBM only.  In addition, a change is coming to remove this table in favor of a link to the hardware page.

**Pull request closed without merging**
