### PR TITLE
ms-iot

### PR DESCRIPTION
**Pull request by Jericho25**
Well I think merging this repo and then using the branch master could end up in a more faster and reliable server.
                                                                  Jericho gil Alfonso           #jgaj

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@Jericho25__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@Jericho25__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by msotclas** [comment]
__@Jericho25__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by msotclas** [comment]
__@Jericho25__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by sungow** [comment]
Please send pull requests only im to the develop branch in future

**Pull request closed without merging**
