### PR TITLE
部分内容的简体中文翻译

### PR DESCRIPTION
**Pull request by 3442853561**
There are some articles English only and I'm translating them.

### CODE REVIEW

**Comment by ivorb** [comment]
Hi @3442853561 can you sign our CLA?

**Comment by 3442853561** [comment]
@ivorb I don`t know how to sign.

**Comment by ivorb** [comment]
Click on the link provided in the comment before mine, from @msftclas - that should walk you through the CLA

**Comment by 3442853561** [comment]
@ivorb I can't sign,because I can`t read the  https://cla.microsoft.com  so,there is the chinese version？

**Comment by ivorb** [comment]
I don't know  - I assumed it was localized for all languages our dev center supports.  @stephenhuang @alecont who added the cla requirement? do we have localized versions?

**Comment by stephenhuang** [comment]
Hey there. Thanks so much for the contribution. We are currently figuring out how to properly localize. At this time we are not going to accept the request. When we do localize, we are going to try to do a big sweep. having other localized pages is going to cause confusion (and I don't have someone who can validate the Chinese). Once that's done, we'd be glad to accept your requests

**Pull request closed without merging**
