### PR TITLE
Update BoardComparison.md

### PR DESCRIPTION
**Pull request by ghost**
https://developer.qualcomm.com/forum/qdn-forums/hardware/iot-development-platform/29652

"At this time, 720p is the highest resolution supported. Timing for 1080p support has not yet been determined."

### CODE REVIEW

**Comment by alecont** [comment]
Daniel will take a look at this one.

**Comment by dankuo** [comment]
Thanks for the correction. Can you please resolve the merge issues first though?

**Comment by ivorb** [comment]
@cyberh0me Board comparison actually doesn't exist anymore.  Could you make the updates to Device Options (explore/deviceoptions)?

**Comment by ghost** [comment]
7 months later...
"HDMI (16:9 @ 1280x720 recommended)" I would replace recommended with supported as this is really a limitation compared with the other boards

**Comment by ivorb** [comment]
We've been waiting for resolution of merge conflicts - could you sync with the latest?

**Comment by ghost** [comment]
already synced....

**Comment by ivorb** [comment]
It appears we still have merge conflicts - this file I believe is no longer in the root en-US folder, but now in the en-US/Explore/ directory.  Will you please merge your changes into that file?

**Pull request closed without merging**
