### PR TITLE
MCP23017 Sample

### PR DESCRIPTION
**Pull request by IoTGirl**

### CODE REVIEW

**Comment by IoTGirl** [comment]
DO NOT PULL: Please render for me! It is failing with 404 on my GH Pages.

**Comment by zfields** [comment]
looks good to me

**Comment by IoTGirl** [comment]
Thanks Zak!

**Comment by IoTGirl** [comment]
Hi Lou,

It looks like a later change has removed the MCP23017 sample from the sampleapps page.

Justine

**Pull request closed without merging**
