### PR TITLE
Work this out..

### PR DESCRIPTION
**Pull request by Jericho25**
Please commit to #master  Thank you..  

                                                                    #jgaj

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@Jericho25__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@Jericho25__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by msotclas** [comment]
__@Jericho25__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by msotclas** [comment]
__@Jericho25__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by ooeygui** [comment]
Could you resubmit this to the develop branch instead of gh-pages?

**Pull request closed without merging**
