### PR TITLE
Correct formatting

### PR DESCRIPTION
**Pull request by CedricMi**
- Show the sharp in title 'Using the class from c#'
- Show the images

### CODE REVIEW

**Comment by ivorb** [comment]
@CedricMi Thanks for noticing this!  Definitely need to fix the top links like you did, and the two images not showing up (c++ClassWizard and NewC++Class), however the other images should remain relative wherever possible.  See https://developer.microsoft.com/en-us/windows/iot/win10/samples/arduino-wiring/ArduinoWiringComponents 

Could you update this PR to use site.baseurl instead of the absolute url?  Otherwise I'll take some of your changes, but retain the relative links for the rest of them.

Thanks!

**Comment by CedricMi** [comment]
I did as you asked, but it seems to me the images do not show again.

Maybe there's something wrong with the configuration of {{site.baseurl}}  ?

Sorry these are my first steps in github formatting & pulls.

**Comment by alecont** [comment]
what about we just rename the two pngs that have "++" in the name? better to call them Cpp...

**Comment by alecont** [comment]
I have a similar PR with the rename: https://github.com/ms-iot/content/pull/902

**Comment by ivorb** [comment]
Cedric, thanks for your contribution! Ale has created a similar PR that has now been merged, so if there are more changes that you suggest we make, will you please create a new PR?

**Pull request closed without merging**
