### PR TITLE
Correct CPU/GPU frequencies for Raspberry Pi 3.

### PR DESCRIPTION
**Pull request by bearnard**
Minor copy pasta corrections.

### CODE REVIEW

**Comment by ivorb** [comment]
@alecont can you verify these for me?

**Comment by alecont** [comment]
good to go. I'm going to merge.

**Comment by alecont** [comment]
ah... need to resolve the conflicts first...

**Comment by ivorb** [comment]
I'll handle the conflicts if you don't have the time Ale - as long as its verified!

**Comment by ivorb** [comment]
Thanks @bearnard for your contribution!  I had to merge this manually, which is now done, so closing out the PR

**Comment by bearnard** [comment]
Great, Thanks.

**Pull request merged**
