### PR TITLE
keclay Patch 1

### PR DESCRIPTION
**Pull request by kcc1988**
Add Alljoyn samples/tutorials - 2 new pages created (ZWave and GPIO tutorials), pics added. Alljoyn.md page has been edited so that the samples have been removed

### CODE REVIEW

**Comment by ghost** [comment]
Hi **@kcc1988**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by sungow** [comment]
HI, the images in the commit look very stretched and bit blurry is it possible to add better images ?

**Comment by kcc1988** [comment]
sungow,

It's interesting that the images do look stretchy in the commit but are fine if I open them on my desktop or view them within my private branch on the GitHub site. Are we sure these will be rendered looking stretchy on the tutorial pages? Can they just be checked in anyway?

**Comment by kcc1988** [comment]
sungow, the images look fine

**Comment by ghost** [comment]
Hi **@kcc1988**, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by kcc1988** [comment]
sungow,

It's interesting that the images do look stretchy in the commit but are
fine if I open them on my desktop or view them within my private branch on
the GitHub site. Are we sure these will be rendered looking stretchy on the
tutorial pages? Can they just be checked in anyway?

**Pull request merged**
