### PR TITLE
Add GoPiGo and GrovePi to List of Devices

### PR DESCRIPTION
**Pull request by ghost**
Adding in GoPiGo and GrovePi.

### CODE REVIEW

**Comment by DexterInd** [comment]
Thank you @msftclas we await the reply of your real human masters.

**Comment by ivorb** [comment]
@alecont could you assign an SME to verify this?

**Comment by alecont** [comment]
yep, getting to this soon :-)

**Comment by DexterInd** [comment]
We are around and happy to answer any questions about this!

**Pull request merged**
