### PR TITLE
Update links to version 1.0.1.5 of AllJoyn Explorer application

### PR DESCRIPTION
**Pull request by zhuridartem**
Update links to version 1.0.1.5 of AllJoyn Explorer application.
Making the link names consistent for all AllJoyn sample pages.

### CODE REVIEW

**Comment by ooeygui** [comment]
@zhuridartem Please signed the updated CLA at http://cla.microsoft.com

**Comment by zhuridartem** [comment]
Done. Please approve.

**Comment by ooeygui** [comment]
I'm looking to see why the bot has not removed the block.

**Comment by ooeygui** [comment]
This has been confirmed signed. We're looking to see why the bot isn't updating; I'm going to hold off pulling until we see what's going on.

**Comment by zhuridartem** [comment]
Any update?

**Comment by ooeygui** [comment]
Pulled with confirmation from CLA

**Pull request merged**
