### PR TITLE
spaces BUG

### PR DESCRIPTION
**Pull request by Blackcode**
Path containing spaces BUG warning

### CODE REVIEW

**Comment by ooeygui** [comment]
Hi there,
Thank you for the submission! This is a good change. We normally require a contribution license agreement on file (https://cla.msopentech.com/). However, I'm checking to see if fixes like this require an agreement on file.

**Comment by Blackcode** [comment]
hi man,
i had my cla filled with the last commit i did the kill\list task but i had to refork for this one.
(I hope you do not mean that for every pull request I make, I have to complete a CLA :) )

**Comment by ooeygui** [comment]
You didn't happen to add your github account to the CLA? (I'm not able to find it in the database right now. I'm going to check with the maintainer)

**Comment by ooeygui** [comment]
Found it. Thank you for submitting!!!

**Comment by Blackcode** [comment]
np.... when these merges will be available online...

**Comment by ooeygui** [comment]
We move code from develop to master (or for the content pages gh-pages) every other week. Our sprint ended today (friday), so we'll do a pass on Tuesday (due to holiday), then push. You should see it Tuesday evening.

Thanks again!

**Pull request merged**
