### PR TITLE
Patch 1 - Fixed pic links for ZWave tutorial

### PR DESCRIPTION
**Pull request by kcc1988**
@sungow Some images appear to have disappeared, correcting the links with this pull request

### CODE REVIEW

**Comment by kcc1988** [comment]
@daveraskin requesting a merge ASAP for quality validation

**Comment by daveraskin** [comment]
I merged into develop branch for testing.  Still appear to be a lot of missing images at "http://ms-iot.github.io/content/en-US/win10/samples/ZWaveTutorial.htm"

**Comment by kcc1988** [comment]
@daveraskin Yesterday I noticed that while the changes were seen in the content-develop branch immediately it look a while for them to show up on the ms-iot.github.io site. I didn't see them until Sunitha explicitly checked the merge changes into main (I think). Should I see them already?

**Comment by daveraskin** [comment]
They should be up starting now.  Thanks.

**Comment by kcc1988** [comment]
Thanks!

**Pull request merged**
