### PR TITLE
Added Task List/Kill

### PR DESCRIPTION
**Pull request by Blackcode**
Added Task List/Kill on AdvancedUsage - Customized experience

### CODE REVIEW

**Comment by anthony-ngu** [comment]
Your two commits https://github.com/Blackcode/content/commit/b2f3c3d922809f04b2f3bc74d465b5097ecbcea8 and https://github.com/Blackcode/content/commit/722263a61e18c4bd0f2c4ada5ce5403e4242d8a8 negate each other, so my suggestion would be to remove those from your pull-request for clarity and to rename the https://github.com/Blackcode/content/commit/f7f350ed0156474566d942ebb1529bafa185a9bb commit with the "Added Task List/Kill in Customized Experience" title.

I think this new section would be helpful for users who don't know about the tlist / kill functionality! :+1:

**Comment by zfields** [comment]
Great contribution! However, I would like see a single commit that didn't change all the lines, so we can see only the lines you've changed. Do you know if you changed the line endings or set tabs to spaces or spaces to tabs?

**Comment by Blackcode** [comment]
Hi guys I'm using Tortoise SVN and I'm kinda new to it. I did a mess trying to commit to Github. As for the single commit I will check what is the problem since I used Dreamweaver to edit the code.

**Comment by Blackcode** [comment]
I will close this pull request and reopen...

Edit: check the new Pull should be ok now

**Pull request closed without merging**
