### PR TITLE
New Sample App - Smart Fan

### PR DESCRIPTION
**Pull request by schultetwin1**
Created a new sample app using basic Arduino components. This fan can be programmed to turn on and off based on temperature and light.

### CODE REVIEW

**Comment by anthony-ngu** [comment]
This is an awesome sample. 

I see you have a section on optional Add-Ons to the project. Do you have information on them that can be placed inside those sections?

Also, please fill out a CLA Agreement (which can be found here https://cla.msopentech.com/) in order to allow us to merge the pull-request.

Thanks for your interest in contributing!

**Comment by schultetwin1** [comment]
There is a little bit of information for optional addons. I haven't done these however so I don't have too much info. I can take that out for now if you want.

I also filled out the CLA and have updated the branch to fix merge conflicts.

**Comment by anthony-ngu** [comment]
Since those areas are placeholders for future information, please leave them out until there is useful information.

Thanks!

**Comment by ooeygui** [comment]
CLA confirmed

**Pull request merged**
