### PR TITLE
Updated PowerShell Page

### PR DESCRIPTION
**Pull request by merzink**
Updated PowerShell page to include Known Issues section

### CODE REVIEW

**Comment by ooeygui** [comment]
To pull this, I need the following:
- Please sign the contribution license agreement at cla.microsoft.com
- Please add your full name and email address.

**Comment by merzink** [comment]
Hey Lou,

I did this step already and am getting errors with the DocuSign email link to sign. I've submitted a request already for support.

Let me know if there's anything else I can do.

Thanks,
Merzin

Sent from my Windows Phone

**Comment by ooeygui** [comment]
Ping me at MS, and we'll send mail to the CLA owners to see what's going on. (Can't pull it while tagged CLA-required)

**Comment by merzink** [comment]
Sure, let me add you to the thread I started with them.

Sent from my Windows Phone

**Comment by ghost** [comment]
**@merzink**, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Pull request merged**
