### PR TITLE
Added required language for store requirements; Formatting updates

### PR DESCRIPTION
**Pull request by trmck**
Missing language for OEM Store Preinstall requirements added
Updated formatting to support "Note" callout

### CODE REVIEW

**Comment by ivorb** [comment]
had a similar PR that changed the spacing of management as well, and that has already been merged. could you sync your fork and resolve any conflicts from that?

**Comment by trmck** [comment]
Sure.

**Comment by trmck** [comment]
Hi Ivor,

How soon can the PR submitted for the store page get approved. The store team is receiving an influx of requests due to the old language.

Best,
Tre`Von

Sent from Outlookhttps://aka.ms/kr63o9 on iOS

**Comment by ivorb** [comment]
@trmck it looks like I can't merge this automatically - can you pull in the most recent and fix any conflicts?  Then I'm happy to merge it in after a quick review

**Comment by trmck** [comment]
See #955

**Comment by ivorb** [comment]
great thanks!

**Pull request closed without merging**
