### PR TITLE
zh-CN manual had been created!

### PR DESCRIPTION
**Pull request by xgqfrms**
**http://ms-iot.github.io/content/zh-CN/win10/GetStartedManually.htm**

### CODE REVIEW

**Comment by xgqfrms** [comment]
ok ？

**Comment by ivorb** [comment]
@xgqfrms Please sign the CLA linked above before we can merge this change.

@stephenhuang could you have an SME take a look at this change?  If it's just a translation into Chinese, we'll get it after loc handsback

**Comment by alecont** [comment]
Stephen will take a look.

**Comment by stephenhuang** [comment]
Hey there. Thanks so much for the contribution. We are currently figuring out how to properly localize. At this time we are not going to accept the request. When we do localize, we are going to try to do a big sweep. having other localized pages is going to cause confusion (and I don't have someone who can validate the Chinese). Once that's done, we'd be glad to accept your requests

**Pull request closed without merging**
