### PR TITLE
Update TurnkeySecurity.md

### PR DESCRIPTION
**Pull request by ghost**
irreversible in what context ?
https://social.msdn.microsoft.com/Forums/en-US/d26be5f4-0a92-4d2c-ba44-57b0c3f24fe0/flashing-the-dragonboard-410c-after-you-provision-rpmb?forum=WindowsIoT

should we add the mentioned procedure in the docs ?

### CODE REVIEW

**Comment by alanch-ms** [comment]
It's "irreversible" in the sense that physical fuses on the dragonboard are blown.  Once RPMB has been provisioned, it cannot be unprovisioned.

**Comment by ghost** [comment]
so why was the user from the linked thread able to revert that change ?

**Comment by alanch-ms** [comment]
He didn't.   When you provision RPMB, you enabled TPM and other functionalities.  What he did in the linked thread was to revert the dragonboard to the state as if RPMB was just provisioned.  IE. TPM is still enabled on that dragonboard.

**Comment by ghost** [comment]
ok i am beginning to understand, what if we add the physical fuses on the dragonboard are blown after the italic irreversible step ?
but its also ok if we let the content as it is and close that request ...

**Comment by rachitb777** [comment]
The doc has moved to docs.microsoft.com

**Pull request closed without merging**
