### PR TITLE
Adding AppInstallation.md with instructions for installing an Appx on IoT

### PR DESCRIPTION
**Pull request by mskalra**
Adding AppInstallation.md with instructions based off sample provided in ms-iot/samples/AppInstall

### CODE REVIEW

**Comment by daveraskin** [comment]
@mskalra is this meant to be a standalone page on the website, or is this just content referenced in some other page?

**Comment by mskalra** [comment]
@daveraskin these instructions go hand-in hand with the following sample: https://github.com/ms-iot/samples/tree/develop/AppInstall. Brian asked me to make the corresponding doc changes in ms-iot/content when I made a pull request in ms-iot/samples.

**Comment by daveraskin** [comment]
@mskalra If you want this page to be visible on the ms-iot github pages site, you'll need to include "front-matter" at the top of the file so that the page has a permanent url, a title, etc.  

Here's jekyll's guide to front matter: http://jekyllrb.com/docs/frontmatter/
And here is an example of how we use it on our page: https://raw.githubusercontent.com/ms-iot/content/develop/en-US/GetStarted.md

Make sure to specify the lang as en-US and the layout as Default.  Besides that, choose a page title and a permanent url (likely something along the lines of "/en-US/win10/AppInstall.htm")

thanks!

**Comment by mskalra** [comment]
Thanks @daveraskin will make corresponding changes and send a new pull request

**Pull request closed without merging**
