### PR TITLE
Update Store.md

### PR DESCRIPTION
**Pull request by kreuzhofer**
this documentation was failing for a release build. I had to move the exe file to a subfolder. then it worked. Fixed.

### CODE REVIEW

**Comment by paulmon** [comment]
The updated directions work for VS 2017.  However they don't work for VS 2015.  The document should be updated to indicate that the steps are different for VS 2015 and VS 2017

**Comment by kreuzhofer** [comment]
@paulmon ok, i fixed it.

**Review by parameshbabu — APPROVED** [review]
Looks good.

**Comment by paulmon** [comment]
Thanks!

**Review by bfjelds — APPROVED** [review]

**Pull request merged**
